version: "3.8"

services:
  app:
    build:
      context: ./backend # 올바른 Dockerfile 경로
      dockerfile: Dockerfile
    container_name: gongsta-backend
    ports:
      - "8080:8080" # Spring Boot 서비스 포트
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/zune
      SPRING_DATASOURCE_USERNAME: gongsta
      SPRING_DATASOURCE_PASSWORD: qwer1234
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: zune
      POSTGRES_USER: gongsta
      POSTGRES_PASSWORD: qwer1234
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Nginx 포트
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  database-data:
